// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbcqV_bKEuxOjiJwt6_FY_Xq1KRPrw9Ng',
    appId: '1:943671978858:web:301bd8638a91cd73d89313',
    messagingSenderId: '943671978858',
    projectId: 'gestion-casos-5d432',
    authDomain: 'gestion-casos-5d432.firebaseapp.com',
    storageBucket: 'gestion-casos-5d432.firebasestorage.app',
    measurementId: 'G-EWPQEG9H87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXlnIS5xuMJUDuLAU2muZuSGOH4BoFMls',
    appId: '1:943671978858:android:0a0cd2331616cafcd89313',
    messagingSenderId: '943671978858',
    projectId: 'gestion-casos-5d432',
    storageBucket: 'gestion-casos-5d432.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxe4U--2zRuhuEv1UNFIkneTUpzeM0yQE',
    appId: '1:943671978858:ios:b6e65591260c2144d89313',
    messagingSenderId: '943671978858',
    projectId: 'gestion-casos-5d432',
    storageBucket: 'gestion-casos-5d432.firebasestorage.app',
    iosBundleId: 'com.example.gestionCasos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxe4U--2zRuhuEv1UNFIkneTUpzeM0yQE',
    appId: '1:943671978858:ios:b6e65591260c2144d89313',
    messagingSenderId: '943671978858',
    projectId: 'gestion-casos-5d432',
    storageBucket: 'gestion-casos-5d432.firebasestorage.app',
    iosBundleId: 'com.example.gestionCasos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbcqV_bKEuxOjiJwt6_FY_Xq1KRPrw9Ng',
    appId: '1:943671978858:web:74abc6c3bf00bb60d89313',
    messagingSenderId: '943671978858',
    projectId: 'gestion-casos-5d432',
    authDomain: 'gestion-casos-5d432.firebaseapp.com',
    storageBucket: 'gestion-casos-5d432.firebasestorage.app',
    measurementId: 'G-2FP31S2DF3',
  );
}
